name: VibeZ
options:
  bundleIdPrefix: com.vibez
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
targets:
  VibeZ:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "*.md"
          - "*.sh"
          - "Package.swift"
          - "project.yml"
          - "XCODE_SETUP.md"
          - "README_BUILD.md"
          - "validate_swift.sh"
          - "package_final.sh"
          - "create_xcode_project*.sh"
    frameworks:
      - Foundation
      - SwiftUI
      - Combine
      - AVFoundation
      - AVKit
      - UIKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.vibez.app
      SWIFT_VERSION: "6.0"
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: Info.plist
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_NSMicrophoneUsageDescription: "VibeZ needs microphone access for voice messages and voice chat"
      INFOPLIST_KEY_NSCameraUsageDescription: "VibeZ needs camera access for video chat and avatar photos"
      INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "VibeZ needs photo library access to share images"
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate

